name: Build, Test and Deploy
on:
  # run when the master branch is updated
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    if: "!(github.event.head_commit && contains(github.event.head_commit.message, 'ci skip'))"

    steps:
      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPOSITORY_DISPATCH }}
          event-type: "push-tag"
          client-payload: '{"ref": "refs/tags/latest"}'

      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPOSITORY_DISPATCH }}
          event-type: "push-tag"
          client-payload: '{"ref": "refs/tags/~v7.0.0"}'
