name: Build, Test and Deploy
on:
  # run when the master branch is updated
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    if: "!(github.event.head_commit && contains(github.event.head_commit.message, 'ci skip'))"
    steps:
    steps:
      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: "https://api.github.com/repos/qooxdoo/qxl.apiviewer/dispatches"
          event-type: "push-tag"
          client-payload: '{"ref": "refs/tags/latest"}}'

      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: "https://api.github.com/repos/qooxdoo/qxl.apiviewer/dispatches"
          event-type: "push-tag"
          client-payload: '{"ref": "refs/tags/v7.0"}}'
