name: Publish new version of documentation
on:
  repository_dispatch:
    types:
      - push-tag
jobs:
  publish_docs:
    name: Publish tagged documentation
    runs-on: ubuntu-latest
    steps:
      - name: Install Playwright Dependencies
        uses: microsoft/playwright-github-action@v1

      - id: get_version
        run: |
          ref=${{ github.event.client_payload.ref }}
          version=$(echo "$ref" | cut -d / -f 3)
          version=$(echo "$version" | cut -d ~ -f 2)
          dir=$(echo "$version" | cut -d . -f 1-2)
          echo "::set-output name=version::$version"
          echo "::set-output name=destination_dir::$dir"
          
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          
      - name: output config
        run: |
          node --version
          npm --version
          echo "destination version is ${{ steps.get_version.outputs.version }}"
          echo "destination dir is ${{ steps.get_version.outputs.destination_dir }}"
          
      - name: add compiler
        run: |
             npm install @qooxdoo/framework@${{ steps.get_version.outputs.version }}        
             npx qx --help || npm install @qooxdoo/compiler
             
      - name: Build API Viewer
        run:  npx qx deploy --target=build -v --clean
        
      - name: Run Tests
        run: npx qx test --target=build -v 

      - name: Deploy to GH page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
          destination_dir: ${{ steps.get_version.outputs.destination_dir }}


